name: Publish prerelease packages on NPM

permissions:
  contents: read
  packages: read

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc
          npm config set access public

      - name: Publish browser package
        if: startsWith(github.ref_name, 'openfeature-browser@')
        run: |
          cd packages/browser
          npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish core package
        if: startsWith(github.ref_name, 'flagging-core@')
        run: |
          cd packages/core
          npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Display Invalid Package Error
        if: !startsWith(github.ref_name, 'openfeature-browser@') && !startsWith(github.ref_name, 'flagging-core@')
        run: |
          echo "❌ Invalid tag format: '${{ github.ref_name }}'"
          echo "✅ Expected format: <package name>@<semantic-version>"
          echo ""
          echo "Acceptable package names:"
          echo "   - openfeature-browser"
          echo "   - flagging-core"
          echo ""
          echo "Example tags:"
          echo "   - openfeature-browser@0.1.0-alpha.2"
          echo "   - flagging-core@0.1.0-alpha.1"
          exit 1
