name: Publish packages on NPM

permissions:
  contents: read
  metadata: read
  packages: read

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@60edb5dd5452c9c546f5f0e864dca308dbe4f774 # v4.2.0
        with:
          node-version: "18.x"
      - run: yarn config set npmAuthToken $NPM_PUBLISH_TOKEN
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - run: yarn
      - run: yarn npm publish
